# Generated by Django 5.0.7 on 2024-07-11 04:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_hotelin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas', models.PositiveIntegerField()),
                ('dipesan_pada', models.DateTimeField(default=django.utils.timezone.now)),
                ('alamat_pengiriman', models.TextField()),
                ('status_pesanan', models.CharField(default='Menunggu Pembayaran', max_length=100)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_hotelin.produk')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode_pembayaran', models.CharField(max_length=100)),
                ('tanggal_pembayaran', models.DateTimeField(blank=True, null=True)),
                ('status_pembayaran', models.CharField(default='Belum Dibayar', max_length=100)),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_hotelin.pemesanan')),
            ],
        ),
        migrations.DeleteModel(
            name='karyawan',
        ),
        migrations.DeleteModel(
            name='pelanggan',
        ),
        migrations.DeleteModel(
            name='pesanan',
        ),
    ]
