# Generated by Django 5.0.7 on 2024-07-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_hotelin', '0002_pemesanan_transaksi_delete_karyawan_delete_pelanggan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemesanan',
            name='alamat_pengiriman',
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='status_pesanan',
            field=models.CharField(choices=[('Menunggu Pembayaran', 'Menunggu pembayaran'), ('Sedang diproses', 'Sedang diproses'), ('Selesai', 'Selesai')], default='Menunggu pembayaran', max_length=100),
        ),
    ]
