# Generated by Django 5.0.7 on 2024-07-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_hotelin', '0003_remove_pemesanan_alamat_pengiriman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='status_pesanan',
            field=models.CharField(default='Menunggu Pembayaran', max_length=100),
        ),
    ]
