# Generated by Django 5.0.7 on 2024-07-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_hotelin', '0004_alter_pemesanan_status_pesanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='metode_pembayaran',
            field=models.CharField(default='cash', max_length=100),
        ),
    ]
