# Generated by Django 5.0.7 on 2024-07-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_hotelin', '0008_alter_produk_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='user',
        ),
    ]
