# Generated by Django 5.0.7 on 2024-07-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_hotelin', '0010_rename_pesanan_transaksi_pemesanan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaksi',
            old_name='pemesanan',
            new_name='pesanan',
        ),
    ]
